### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by s79ns** [s79ns/chat-space#9]
#IPアドレス
54.150.116.181

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①新規グループ作成ページにて、チェックボックスではなくインクリメンタルサーチにてユーザーが追加できるようにしましょう**
現在の様子↓
![スクリーンショット 2020-07-15 15 29 43](https://user-images.githubusercontent.com/49669977/87511699-b74c5c00-c6b0-11ea-9f90-bc37ca678936.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by s79ns** [comment]
ご指摘ありがとうございます。修正いたしました！
![指摘箇所の修正](https://user-images.githubusercontent.com/67348810/87532713-867b1f80-c6ce-11ea-99bd-2d0faf57900a.gif)

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
